version: '3.7'

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
  web:
    image: "andrewnagata/omakase_web:latest"
    container_name: web
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    container_name: api